export { default as DocenTitleBar } from "./title-bar";
export { default as DocenDialog } from "./dialog";
export { default as DocenWorkspace } from "./workspace";
export { default as DocenDocumentArea } from "./document-area";
export { default as DocenTaskPane } from "./task-pane";
export { default as DocenNavigationPane } from "./navigation-pane";
export { default as DocenCommentsPane } from "./comments-pane";
export { default as DocenRevisionsPane } from "./revisions-pane";
export { default as DocenFindReplaceDialog } from "./find-replace-dialog";
export { default as DocenStatusBar } from "./status-bar";
export { default as DocenCommandSearch } from "./command-search";
export { default as DocenOptionsDialog } from "./options-dialog";
export { default as DocenAutocorrectDialog } from "./autocorrect-dialog";
export { default as DocenQuickPartDialog } from "./quick-part-dialog";
export { default as DocenBuildingBlocksDialog } from "./building-blocks-dialog";
export { default as DocenWordCountDialog } from "./word-count-dialog";
export { default as DocenSymbolDialog } from "./symbol-dialog";
export { default as DocenMeasureInput } from "./measure-input";
export { default as DocenParagraphDialog } from "./paragraph-dialog";
export { default as DocenPageSetupDialog } from "./page-setup-dialog";
export { default as DocenTableDialog } from "./table-dialog";
export { default as DocenColumnsDialog } from "./columns-dialog";
export { default as DocenLinkDialog } from "./link-dialog";
export { default as DocenZoomDialog } from "./zoom-dialog";
export { default as DocenClipboardPane } from "./clipboard-pane";
export { default as DocenSpellingPane } from "./spelling-pane";
export { default as DocenThesaurusPane } from "./thesaurus-pane";
export { default as DocenLanguageDialog } from "./language-dialog";
export { default as DocenDateTimeDialog } from "./date-time-dialog";
export { default as DocenTocDialog } from "./toc-dialog";
export { default as DocenPhoneticDialog } from "./phonetic-dialog";
export { default as DocenTwoInOneDialog } from "./two-in-one-dialog";
export { default as DocenDefineListDialog } from "./define-list-dialog";
export { default as DocenCaptionDialog } from "./caption-dialog";
export { default as DocenNoteDialog } from "./note-dialog";
export { default as DocenNoteSettingsDialog } from "./note-settings-dialog";
export { default as DocenLineNumbersDialog } from "./line-numbers-dialog";
export { default as DocenPageNumberFormatDialog } from "./page-number-format-dialog";
export { default as DocenFieldDialog } from "./field-dialog";
export { default as DocenChartDataDialog } from "./chart-data-dialog";
export { default as DocenChartTypeDialog } from "./chart-type-dialog";
export { default as DocenCompressPicturesDialog } from "./compress-pictures-dialog";
export { default as DocenCrossReferenceDialog } from "./cross-reference-dialog";
export { default as DocenSourcesDialog } from "./sources-dialog";
export { default as DocenRecipientsDialog } from "./recipients-dialog";
export { default as DocenMergeFieldDialog } from "./merge-field-dialog";
export { default as DocenPasteSpecialDialog } from "./paste-special-dialog";
export { default as DocenFontDialog } from "./font-dialog";
export { default as DocenTablePropertiesDialog } from "./table-properties-dialog";
export { default as DocenDrawingPropertiesDialog } from "./drawing-properties-dialog";
export { default as DocenDistributeDialog } from "./distribute-dialog";
export { default as DocenLayoutOptionsFlyout } from "./layout-options-flyout";
export { default as DocenBordersShadingDialog } from "./borders-shading-dialog";
export { default as DocenWatermarkDialog } from "./watermark-dialog";
export { default as DocenFillEffectsDialog } from "./fill-effects-dialog";
export { default as DocenInspectDialog } from "./inspect-dialog";
export { default as DocenTemplateDialog } from "./template-dialog";
export { default as DocenModifyStyleDialog } from "./modify-style-dialog";
export { default as DocenNewStyleDialog } from "./new-style-dialog";
export { default as DocenHyphenationDialog } from "./hyphenation-dialog";
export { default as DocenTabsDialog } from "./tabs-dialog";
export { default as DocenBookmarkDialog } from "./bookmark-dialog";
export { default as DocenGoToDialog } from "./go-to-dialog";
export { default as DocenPropertiesDialog } from "./properties-dialog";
export { DocenSdtDialog } from "./sdt-dialog";
export { DocenNavPages } from "./nav-pages";
export { DocenRevealFormattingPane } from "./reveal-formatting-pane";
export { DocenCompareDialog } from "./compare-dialog";
export { DocenRestrictEditingPane } from "./restrict-editing-pane";
export { DocenSignatureLineDialog } from "./signature-line-dialog";
export { DocenDropCapDialog } from "./dropcap-dialog";
export { DocenMergeRecipientsDialog } from "./merge-recipients-dialog";
export { DocenVersionHistoryDialog } from "./version-history-dialog";
export { DocenA11yCheckerPane } from "./a11y-checker-pane";
export { DocenMiniToolbar, default as DocenMiniToolbarDefault } from "./mini-toolbar";
export { DocenOutlineView, default as DocenOutlineViewDefault } from "./outline-view";
export { DocenRuler, default as DocenRulerDefault } from "./ruler";
export { DocenNavPane, default as DocenNavPaneDefault } from "./nav-pane";
export { DocenPrintPreview, default as DocenPrintPreviewDefault } from "./print-preview";
export { DocenTranslatePane, default as DocenTranslatePaneDefault } from "./translate-pane";
export { DocenAltTextPane, default as DocenAltTextPaneDefault } from "./alt-text-pane";
export { DocenTouchHandles, default as DocenTouchHandlesDefault } from "./touch-handles";

