#!/usr/bin/env node
// External oracle runner for the DOCX fixture + fuzz harnesses.
//
// Phase A (fixtures): for every fixture generated by fixtures.spec.ts
//   (tests/.temp/oracle/<name>/gen{1,2,3}.docx):
//   - python-docx opens the package; lxml structural signals (oracle.py)
//     must be clean: no XML parse errors, dangling rels or content-type gaps
//   - the fixture's `python` expectations are evaluated against gen1
//   - gen1/gen2/gen3 structural signals must match (rIds canonicalized)
//   - LibreOffice renders all three generations to PDF; pdftotext page text
//     must match across generations and satisfy the fixture's `pdf` checks
//   - LibreOffice re-saves gen1; docen parses and re-generates the resave,
//     which must open again and keep the same rendered text
//
// Phase B (fuzz): every case in tests/.temp/fuzz/manifest.json gets the same
//   package/PDF/resave treatment (bounded by --fuzz-limit / --fuzz-pdf).
//
// Usage:
//   node packages/docx/tests/oracle/run.mjs [--require] [--only a,b]
//     [--skip-fixtures] [--skip-fuzz] [--fuzz-limit N] [--fuzz-pdf N]
//     [--fuzz-resave-every N] [--verbose]
//
// Missing external tools (soffice/pdftotext/python3) skip the checks they
// power with a warning; pass --require to fail instead. The JS half of the
// harness always runs (pnpm exec vp test run oracle fuzz).

import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const DOCX = resolve(HERE, "../..");
const FIXTURES = join(HERE, "fixtures");
const OUT = join(DOCX, "tests", ".temp", "oracle");
const FUZZ = join(DOCX, "tests", ".temp", "fuzz");
const ORACLE_PY = join(HERE, "oracle.py");
const LO_PROFILE = join(DOCX, "tests", ".temp", "lo-profile");
const DIST = join(DOCX, "dist", "index.mjs");

const args = process.argv.slice(2);
const flag = (name) => args.includes(name);
const value = (name, fallback) => {
  const at = args.indexOf(name);
  return at >= 0 && args[at + 1] !== undefined ? args[at + 1] : fallback;
};
const VERBOSE = flag("--verbose");
const REQUIRE = flag("--require");
const ONLY = value("--only", "")
  .split(",")
  .map((entry) => entry.trim())
  .filter(Boolean);
const FUZZ_LIMIT = Number(value("--fuzz-limit", "0")) || Number.POSITIVE_INFINITY;
const FUZZ_PDF = Number(value("--fuzz-pdf", "2"));
const FUZZ_RESAVE_EVERY = Number(value("--fuzz-resave-every", "4")) || Number.POSITIVE_INFINITY;

const failures = [];
const loWarnings = [];
const skipped = [];
const stats = { fixtures: 0, fuzzCases: 0, pdfs: 0, resaves: 0, pyInspects: 0 };

function fail(scope, message, detail) {
  failures.push({ scope, message, detail: detail ? String(detail).slice(0, 2000) : undefined });
  console.error(`✗ ${scope}: ${message}`);
}

function note(message) {
  console.log(`· ${message}`);
}

function has(cmd) {
  const result = spawnSync("sh", ["-c", `command -v ${cmd}`], { encoding: "utf8" });
  return result.status === 0 && result.stdout.trim() !== "";
}

const tools = {
  soffice: has("soffice") || has("libreoffice"),
  pdftotext: has("pdftotext"),
  python: has("python3"),
};
const missing = Object.entries(tools)
  .filter(([, available]) => !available)
  .map(([name]) => name);
if (missing.length > 0) {
  const message = `missing external tools: ${missing.join(", ")}`;
  if (REQUIRE) {
    fail("tools", message);
  } else {
    skipped.push(message);
    console.log(`⚠ ${message} — dependent checks skipped (--require fails instead)`);
  }
}
const havePdf = tools.soffice && tools.pdftotext;
const soffice = has("soffice") ? "soffice" : "libreoffice";

function run(command, argv, options = {}) {
  const result = spawnSync(command, argv, {
    encoding: "utf8",
    timeout: options.timeout ?? 180_000,
    maxBuffer: 32 * 1024 * 1024,
  });
  if (VERBOSE && result.stdout) console.log(result.stdout.trim());
  return result;
}

// ── external tool wrappers ───────────────────────────────────────────────

const pyCache = new Map();
function inspect(files) {
  const wanted = files.filter((file) => !pyCache.has(file));
  if (wanted.length === 0) return new Map(files.map((file) => [file, pyCache.get(file)]));
  const result = run("python3", [ORACLE_PY, ...wanted], { timeout: 120_000 });
  if (result.status !== 0) {
    fail("oracle.py", `exit ${result.status}`, result.stderr);
    return new Map();
  }
  const lines = result.stdout.split("\n").filter((line) => line.trim() !== "");
  if (lines.length !== wanted.length) {
    fail("oracle.py", `expected ${wanted.length} reports, got ${lines.length}`, result.stdout);
    return new Map();
  }
  wanted.forEach((file, index) => {
    pyCache.set(file, JSON.parse(lines[index]));
    stats.pyInspects++;
  });
  return new Map(files.map((file) => [file, pyCache.get(file)]));
}

function toPdf(docxPath, outDir) {
  if (!havePdf) return undefined;
  mkdirSync(outDir, { recursive: true });
  const result = run(
    soffice,
    [
      "--headless",
      `-env:UserInstallation=file://${LO_PROFILE}`,
      "--convert-to",
      "pdf",
      "--outdir",
      outDir,
      docxPath,
    ],
    { timeout: 180_000 },
  );
  const pdf = join(
    outDir,
    `${docxPath
      .split("/")
      .pop()
      .replace(/\.docx$/, "")}.pdf`,
  );
  const produced = existsSync(pdf) && readFileSync(pdf).byteLength > 0;
  if (!produced) {
    fail("libreoffice", `PDF conversion failed for ${docxPath}`, result.stderr || result.stdout);
    return undefined;
  }
  if (result.status !== 0) {
    // LibreOffice exits nonzero on some valid documents while still exporting
    // a complete PDF (e.g. a 2-column section carrying both a footnote and an
    // endnote reference; its own resave reproduces it). Missing/empty output
    // still fails above; a usable PDF is recorded as a warning.
    loWarnings.push({
      file: docxPath,
      status: result.status,
      note: "LibreOffice exited nonzero but produced a non-empty PDF",
    });
  }
  stats.pdfs++;
  return pdf;
}

function resaveDocx(docxPath, outDir) {
  if (!tools.soffice) return undefined;
  mkdirSync(outDir, { recursive: true });
  const result = run(
    soffice,
    [
      "--headless",
      `-env:UserInstallation=file://${LO_PROFILE}`,
      "--convert-to",
      "docx",
      "--outdir",
      outDir,
      docxPath,
    ],
    { timeout: 180_000 },
  );
  const out = join(
    outDir,
    `${docxPath
      .split("/")
      .pop()
      .replace(/\.docx$/, "")}.docx`,
  );
  if (!existsSync(out)) {
    fail("libreoffice", `DOCX resave failed for ${docxPath}`, result.stderr || result.stdout);
    return undefined;
  }
  if (result.status !== 0) {
    loWarnings.push({
      file: docxPath,
      status: result.status,
      note: "LibreOffice resaved nonzero but produced the DOCX",
    });
  }
  stats.resaves++;
  return out;
}

function pdfPages(pdfPath) {
  if (!tools.pdftotext || !pdfPath) return [];
  const result = run("pdftotext", ["-layout", pdfPath, "-"], { timeout: 60_000 });
  if (result.status !== 0) {
    fail("pdftotext", `failed for ${pdfPath}`, result.stderr);
    return [];
  }
  const raw = result.stdout.split("\f");
  while (raw.length > 0 && raw[raw.length - 1].trim() === "") raw.pop();
  return raw.map(collapse);
}

function collapse(text) {
  return text.replace(/\s+/g, " ").trim();
}

// ── check evaluation ─────────────────────────────────────────────────────

function getPath(root, path) {
  const parts = path
    .replace(/\[(\d+)\]/g, ".$1")
    .split(".")
    .filter(Boolean);
  let current = root;
  for (const part of parts) {
    if (current === null || current === undefined) return undefined;
    current = current[part];
  }
  return current;
}

function compare(a, b) {
  const left = String(a);
  const right = String(b);
  return left < right ? -1 : left > right ? 1 : 0;
}

function deepEqual(a, b) {
  if (Object.is(a, b)) return true;
  if (Array.isArray(a) && Array.isArray(b)) {
    return a.length === b.length && a.every((entry, index) => deepEqual(entry, b[index]));
  }
  if (a && b && typeof a === "object" && typeof b === "object") {
    const keys = new Set([...Object.keys(a), ...Object.keys(b)]);
    for (const key of keys) if (!deepEqual(a[key], b[key])) return false;
    return true;
  }
  return false;
}

function evaluateSignalChecks(scope, checks, signals) {
  for (const check of checks.python ?? []) {
    const actual = getPath(signals, check.path);
    if (check.equals !== undefined && !deepEqual(actual, check.equals)) {
      fail(
        scope,
        `${check.path} != ${JSON.stringify(check.equals)}`,
        `actual: ${JSON.stringify(actual)?.slice(0, 400)}`,
      );
    }
    if (check.contains !== undefined) {
      const hit = Array.isArray(actual)
        ? actual.some((entry) => deepEqual(entry, check.contains))
        : typeof actual === "string" && actual.includes(String(check.contains));
      if (!hit)
        fail(
          scope,
          `${check.path} does not contain ${JSON.stringify(check.contains)}`,
          JSON.stringify(actual)?.slice(0, 400),
        );
    }
    if (check.length !== undefined && (actual?.length ?? -1) !== check.length) {
      fail(
        scope,
        `${check.path} length ${actual?.length} != ${check.length}`,
        JSON.stringify(actual)?.slice(0, 400),
      );
    }
    if (check.truthy !== undefined && Boolean(actual) !== check.truthy) {
      fail(
        scope,
        `${check.path} truthy ${Boolean(actual)} != ${check.truthy}`,
        JSON.stringify(actual)?.slice(0, 400),
      );
    }
  }
}

function evaluatePdfChecks(scope, checks, pages) {
  for (const check of checks.pdf ?? []) {
    const text = pages[check.page - 1];
    if (text === undefined) {
      fail(scope, `page ${check.page} missing (${pages.length} pages)`);
      continue;
    }
    for (const needle of check.contains ?? []) {
      if (!text.includes(needle))
        fail(scope, `page ${check.page} missing ${JSON.stringify(needle)}`, text.slice(0, 300));
    }
    for (const needle of check.notContains ?? []) {
      if (text.includes(needle))
        fail(
          scope,
          `page ${check.page} unexpectedly has ${JSON.stringify(needle)}`,
          text.slice(0, 300),
        );
    }
    for (const pattern of check.regex ?? []) {
      if (!new RegExp(pattern).test(text))
        fail(scope, `page ${check.page} no match /${pattern}/`, text.slice(0, 300));
    }
  }
}

function canonical(value, key = "") {
  if (Array.isArray(value)) {
    const mapped = value.map((entry) => canonical(entry));
    if (key === "parts" || key === "targets") return mapped.slice().sort(compare);
    return mapped;
  }
  if (value && typeof value === "object") {
    const out = {};
    for (const childKey of Object.keys(value)) {
      if (childKey === "file") continue;
      out[childKey] = canonical(value[childKey], childKey);
    }
    return out;
  }
  if (typeof value === "string" && /^rId\d+$/.test(value)) return "rId";
  return value;
}

function compareSignals(scope, leftSignals, rightSignals) {
  const left = canonical(leftSignals);
  const right = canonical(rightSignals);
  if (!deepEqual(left, right)) {
    fail(scope, "structural signals differ across generations", difference(left, right));
  }
}

function difference(a, b, path = "$") {
  if (deepEqual(a, b)) return "";
  if (Array.isArray(a) && Array.isArray(b) && a.length === b.length) {
    for (let i = 0; i < a.length; i++) {
      const text = difference(a[i], b[i], `${path}[${i}]`);
      if (text) return text;
    }
  }
  if (a && b && typeof a === "object" && typeof b === "object") {
    for (const key of new Set([...Object.keys(a), ...Object.keys(b)])) {
      const text = difference(a[key], b[key], `${path}.${key}`);
      if (text) return text;
    }
  }
  return `${path}: ${JSON.stringify(a)?.slice(0, 200)} != ${JSON.stringify(b)?.slice(0, 200)}`;
}

function requireClean(scope, report) {
  if (!report) {
    fail(scope, "no oracle report");
    return false;
  }
  if (report.errors?.length) {
    fail(scope, `oracle errors: ${report.errors.join("; ")}`);
    return false;
  }
  if (report.danglingRels?.length) {
    fail(scope, `dangling relationships: ${JSON.stringify(report.danglingRels).slice(0, 500)}`);
    return false;
  }
  if (report.contentTypeGaps?.length) {
    fail(scope, `content-type gaps: ${report.contentTypeGaps.join(", ")}`);
    return false;
  }
  if (!report.ok) {
    fail(scope, "oracle report not ok");
    return false;
  }
  return true;
}

function samePageText(scope, leftPages, rightPages) {
  if (leftPages.length !== rightPages.length) {
    fail(scope, `page count ${leftPages.length} != ${rightPages.length}`);
    return false;
  }
  for (let i = 0; i < leftPages.length; i++) {
    if (leftPages[i] === rightPages[i]) continue;
    fail(
      scope,
      `page ${i + 1} text differs`,
      `left:  ${leftPages[i].slice(0, 300)}\nright: ${rightPages[i].slice(0, 300)}`,
    );
    return false;
  }
  return true;
}

/**
 * Resave leg: LibreOffice may re-render fields (locale dates), re-order
 * blocks and re-split words in the text layer while preserving the content.
 * Compare the per-page multiset of letters (digits/punctuation ignored) plus
 * the page count — content loss is a failure, formatting churn is not.
 */
function sameLetterBag(scope, leftPages, rightPages) {
  if (leftPages.length !== rightPages.length) {
    fail(scope, `page count ${leftPages.length} != ${rightPages.length}`);
    return false;
  }
  for (let i = 0; i < leftPages.length; i++) {
    const letters = (text) => (text.toLowerCase().match(/\p{L}/gu) ?? []).sort().join("");
    if (letters(leftPages[i]) !== letters(rightPages[i])) {
      fail(
        scope,
        `page ${i + 1} letters differ`,
        `left:  ${leftPages[i].slice(0, 300)}\nright: ${rightPages[i].slice(0, 300)}`,
      );
      return false;
    }
  }
  return true;
}

// ── fixture phase ────────────────────────────────────────────────────────

async function loadDocen() {
  if (!existsSync(DIST)) throw new Error(`missing ${DIST} — run pnpm build first`);
  return import(pathToFileURL(DIST).href);
}

async function runFixtures() {
  if (!existsSync(OUT)) {
    fail("fixtures", `no generated fixtures at ${OUT} — run pnpm exec vp test run oracle first`);
    return;
  }
  const names = readdirSync(FIXTURES, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .filter((name) => ONLY.length === 0 || ONLY.includes(name))
    .sort();
  const docen = await loadDocen();

  for (const name of names) {
    const scope = `fixture ${name}`;
    const dir = join(OUT, name);
    const checks = JSON.parse(readFileSync(join(FIXTURES, name, "checks.json"), "utf8"));
    const gens = [1, 2, 3].map((index) => join(dir, `gen${index}.docx`));
    if (gens.some((file) => !existsSync(file))) {
      fail(scope, `missing gen files in ${dir} — run the fixtures spec first`);
      continue;
    }
    stats.fixtures++;

    const reports = inspect(gens);
    const signals = gens.map((file) => reports.get(file));
    if (!signals.every((report) => requireClean(scope, report))) continue;

    // gen1 structural expectations.
    evaluateSignalChecks(scope, checks, signals[0]);
    // Structural equivalence across generations (relationship ids canonicalized).
    compareSignals(scope, signals[0], signals[1]);
    compareSignals(scope, signals[1], signals[2]);

    if (!havePdf) continue;
    const pages = gens.map((file) => pdfPages(toPdf(file, join(dir, "pdf"))));
    if (pages.some((page) => page.length === 0)) {
      fail(scope, "a generation produced no PDF text");
      continue;
    }
    evaluatePdfChecks(scope, checks, pages[0]);
    if (checks.pdfStable !== false) {
      samePageText(`${scope} gen1→gen2`, pages[0], pages[1]);
      samePageText(`${scope} gen2→gen3`, pages[1], pages[2]);
    }

    // Independent writer round-trip: LibreOffice resave → docen parse →
    // generate → LibreOffice render. Text must survive the resave.
    const resaved = resaveDocx(gens[0], join(dir, "resave"));
    if (!resaved) continue;
    try {
      const json = await docen.parseDOCX(readFileSync(resaved));
      const regen = await docen.generateDOCX(json, { prepare: false });
      const regenPath = join(dir, "resave", "regen.docx");
      writeFileSync(regenPath, regen);
      const report = inspect([regenPath]).get(regenPath);
      requireClean(`${scope} resave-regen`, report);
      if (checks.resaveStable !== false) {
        const regenPages = pdfPages(toPdf(regenPath, join(dir, "resave")));
        sameLetterBag(`${scope} resave text`, pages[0], regenPages);
      }
    } catch (error) {
      fail(`${scope} resave-regen`, `docen threw: ${error.message}`, error.stack);
    }
  }
}

// ── fuzz phase ───────────────────────────────────────────────────────────

async function runFuzz() {
  const manifestPath = join(FUZZ, "manifest.json");
  if (!existsSync(manifestPath)) {
    note("no fuzz manifest (run pnpm exec vp test run fuzz first) — skipping fuzz oracles");
    return;
  }
  const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
  const cases = (manifest.samples ?? []).slice(0, FUZZ_LIMIT);
  const docen = await loadDocen();

  for (const sample of cases) {
    const scope = `fuzz seed ${sample.seed}`;
    const dir = join(FUZZ, "cases", String(sample.seed));
    const gens = [1, 2, 3].map((index) => join(dir, `gen${index}.docx`));
    if (gens.some((file) => !existsSync(file))) {
      fail(scope, "missing generated files");
      continue;
    }
    stats.fuzzCases++;
    const reports = inspect(gens);
    const signals = gens.map((file) => reports.get(file));
    if (!signals.every((report) => requireClean(scope, report))) continue;
    compareSignals(scope, signals[1], signals[2]);

    if (!havePdf || FUZZ_PDF <= 0) continue;
    const pdfGens = gens.slice(0, Math.min(FUZZ_PDF, gens.length));
    const pages = pdfGens.map((file) => pdfPages(toPdf(file, join(dir, "pdf"))));
    if (pages.some((page) => page.length === 0)) {
      fail(scope, "a generation produced no PDF text");
      continue;
    }
    for (let i = 1; i < pages.length; i++) {
      samePageText(`${scope} gen1→gen${i + 1}`, pages[0], pages[i]);
    }

    const index = manifest.samples.indexOf(sample);
    if (index % FUZZ_RESAVE_EVERY !== 0) continue;
    const resaved = resaveDocx(gens[1], join(dir, "resave"));
    if (!resaved) continue;
    try {
      const json = await docen.parseDOCX(readFileSync(resaved));
      const regen = await docen.generateDOCX(json, { prepare: false });
      const regenPath = join(dir, "resave", "regen.docx");
      writeFileSync(regenPath, regen);
      const report = inspect([regenPath]).get(regenPath);
      requireClean(`${scope} resave-regen`, report);
      const regenPages = pdfPages(toPdf(regenPath, join(dir, "resave")));
      sameLetterBag(`${scope} resave text`, pages[0], regenPages);
    } catch (error) {
      fail(`${scope} resave-regen`, `docen threw: ${error.message}`, error.stack);
    }
  }
}

async function main() {
  rmSync(LO_PROFILE, { recursive: true, force: true });
  mkdirSync(LO_PROFILE, { recursive: true });
  if (!flag("--skip-fixtures")) await runFixtures();
  if (!flag("--skip-fuzz")) await runFuzz();

  const report = {
    checkedAt: new Date().toISOString(),
    tools,
    skipped,
    stats,
    failures,
    loWarnings,
  };
  mkdirSync(OUT, { recursive: true });
  writeFileSync(join(OUT, "report.json"), `${JSON.stringify(report, null, 2)}\n`);
  console.log(
    `\n${failures.length === 0 ? "✅" : "❌"} oracles: ${stats.fixtures} fixtures, ${stats.fuzzCases} fuzz cases, ` +
      `${stats.pdfs} PDFs, ${stats.resaves} resaves, ${stats.pyInspects} python inspections, ${failures.length} failures`,
  );
  if (skipped.length > 0) console.log(`   skipped: ${skipped.join("; ")}`);
  if (loWarnings.length > 0) {
    console.log(`   libreoffice warnings: ${loWarnings.length} (nonzero exit, PDF produced)`);
  }
  process.exit(failures.length === 0 ? 0 : 1);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
