export { default as DocenRibbon } from "./ribbon";
export { default as DocenRibbonPanel } from "./ribbon-panel";
export { default as DocenRibbonGroup } from "./ribbon-group";
export { default as DocenRibbonButton } from "./ribbon-button";
export { default as DocenRibbonCheckbox } from "./ribbon-checkbox";
export { default as DocenRibbonToggleButton } from "./ribbon-toggle-button";
export { default as DocenRibbonMenu } from "./ribbon-menu";
export { default as DocenRibbonSplitButton } from "./ribbon-split-button";
export { default as DocenRibbonCombobox } from "./ribbon-combobox";
export { default as DocenRibbonInput } from "./ribbon-input";
export { default as DocenColorPicker } from "./color-picker";
export { default as DocenRibbonGallery } from "./gallery";
export { default as DocenKeyTips } from "./key-tips";
export { registerIcon, ribbonIcon } from "./icons";
